### ISSUE TITLE
This is wonderful!

### ISSUE THREAD

**Issue by ruidazeng** [Dmium/StalinSort#3]
I saw that idea by **mathew mastodon.social** on social media as well. Was about to implement it but stumbled upon this repo. Very creative!

In addition, have you considered implementing this algorithm/method in other languages as of yet (in addition to Python)?

**Comment by Dmium** [comment]
I'm planning to redo the python implementation to make a more useful method (And not use del cause I don't like it). Feel free to fork and PR with other languages but yes I'll probably do some other languages at some point.

**Comment by ruidazeng** [comment]
Amazing! Thanks for the information.

In addition, I stumbled upon this repository which contains the open source StalinSort project in a multitude of languages as well: https://github.com/gustavo-depaula/stalin-sort

**Comment by Dmium** [comment]
Looks like someone has invested much more than I have :P
